### ISSUE TITLE
Mosaic crystal does not work in mac

### ISSUE THREAD

**Issue by srio** [srio/ShadowOui-Tutorial#13]

**Comment by lucarebuffi** [comment]
I have this error, it means that the script does not create the proper file, or, the control on the file format must be modified.

**Comment by lucarebuffi** [comment]
![screen shot 2016-09-30 at 23 49 48](https://cloud.githubusercontent.com/assets/6713598/19008023/b80c21c4-8768-11e6-90a2-b096059e175a.png)

**Comment by lucarebuffi** [comment]
I fixed the problem in the congruence checks.

is it the expected result?

![screen shot 2016-10-01 at 00 12 56](https://cloud.githubusercontent.com/assets/6713598/19008494/ed24bd00-876b-11e6-9feb-fc6b223fafaa.png)

**Comment by srio** [comment]
yes, perfect, thanks a lot!!!
